name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install
        run: npm install
      - name: lint
        run: npm run lint

  test_production:
    name: Test production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install
        run: npm install
      - name: Install ANTLR4
        run: pip install antlr4-tools
      - name: Build
        run: npm run build
      - name: Run integration
        run: npm run test:integration
      - name: Run tests
        run: npm run test:browser

  test_linux:
    name: Test on Linux with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20, 22]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: Install
        run: npm install
      - name: Run tests
        run: npm run test:node

  test_macos:
    name: Test on MacOS with Node 18
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install
        run: npm install
      - name: Run tests
        run: npm run test:node

  test_windows:
    name: Test on Windows with Node 18
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install
        run: npm install
      - name: Run tests
        run: npm run test:node
